server:
  port: 80
spring:
  application:
    name: study-service-daily
  #数据库相关配置
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.148:3306/livedb?characterEncoding=UTF-8&ServerTimeZone=Asia/shanghai
      username: root
      password: bzt#2016
      initialSize: 4
      minIdle: 4