#服务名称
spring:
  application:
    name: study-service-work

#服务端口号
server:
  port: 8000

#eureka服务地址
eureka:
  instance:
    hostname: study-service-work-host
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
