server:
  port: 10086
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.148:3306/livedb?characterEncoding=utf-8&ServerTimeZone=Asia/shanghai
      username: root
      password: bzt#2016
      initialSize: 4
      minIdle: 4
      maxActive: 30
      statViewServlet:
        loginPassword: testAdmin
