server:
  port: 10086
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&ServerTimeZone=Asia/shanghai
      username: root
      password: bzt#2016
      initialSize: 4
      minIdle: 4
      maxActive: 30
      statViewServlet:
        loginPassword: testAdmin
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&ServerTimeZone=Asia/shanghai
    username: root
    password: bzt#2016