server:
  port: 80
spring:
  application:
    name: study-service-daily
  #数据库相关配置
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
      username: root
      password: password
      initial-size: 8
      min-idle: 6
      max-active: 16
  # redis相关配置
  redis:
    host: localhost
    password: redis
    port: 6379
#mybatis
mybatis:
  #  mybatis的数据库映射地址
  mapper-locations: classpath:mapper/*Mapper.xml
  #  实体类地址
  type-aliases-package: com.xin.daily.entity

